### ISSUE TITLE
Integration breaks

### ISSUE THREAD

**Issue by Xylemon** [JohnDDuncanIII/Orthodox#7]
I've tried this out, and the old Orthodox seemed to work fine for me but with the lack of some icons. Trying this out got me excited as it seemed like a continuation  but sadly, it seems like a lot of UI elements are hard coded making my GTK2 integrated Seamonkey look completely wonky. Things like my NoScript popup or tabs loose their themeing. I guess I'm asking if you could make version for users who just want a slightly updated version of the old Orthodox theme. Here's an example of the problem:

Normal properly themed experience:
https://i.imgur.com/kW1VPDg.png

New Orthodox theme:
https://i.imgur.com/GodSlA9.png

**Comment by Xylemon** [comment]
Oh, it seems this is already covered in #5. I'll close this, sorry didn't notice.

**Comment by JohnDDuncanIII** [comment]
Yeah sorry, this is a known issue. There are a few files that I believe I could swap out for the originals (it was horribly bad on OS X when I first downloaded it -- particularly the tabs). I'll let you know when there is a proper UNIX version to test.
